---
# handlers file for ntp

- name: ntp | service | restart chrony
  service:
    name: "{{ ntp_daemon }}"
    state: restarted
  when: ntp_enabled | bool

- name: ntp | service | restart cron
  service:
    name: "{{ ntp_cron_daemon }}"
    state: restarted
  when: ntp_cron_handler_enabled | bool
