---
# tasks for NTP to be provided using chrony

- name: ntp | gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "main.yml"
  tags: vars

- name: ntp | configuration | set timezone
  timezone:
    name: "{{ ntp_timezone }}"
  notify: ntp | service | restart cron

- name: ntp | package | install chrony
  package:
    name: "{{ ntp_package }}"
    state: present

- name: ntp | service | run and enable chrony
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes
  when: ntp_enabled | bool

- name: ntp | config | configure chrony
  template:
    src: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.chrony.conf.j2"
    dest: "{{ ntp_config_file }}"
    owner: root
    group: root
    mode: 0640
    backup: yes
  notify: ntp | service | restart chrony
  when: ntp_enabled | bool
